# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main
pr: none
pool: 'default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: build
    displayName: Build
    jobs:
    - job: Build
      pool: 'default'
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '$(solution)'
          feedsToUse: 'select'
          vstsFeed: '5d472129-f05e-4dfb-87be-99999c7da2dd'
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: "$(System.DefaultWorkingDirectory)/src/bielu.multiRummykub.BlazorApp"
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: "$(System.DefaultWorkingDirectory)/src/bielu.multiRummykub.BlazorApp"
          customCommand: 'run build'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '$(solution)'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '—output $(Build.ArtifactDirectory)'
      - task: PublishBuildArtifacts@1
        displayName: "Publishing"
        inputs:
          pathtoPublish: "$(Build.ArtifactStagingDirectory)"
  - stage: deploy
    displayName: Deploy
    jobs:
      - deployment: deploy
        environment: dev  
        pool: default
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
                - task: ExtractFiles@1
                  inputs:
                    archiveFilePatterns: '**/*.zip'
                    destinationFolder: '/var/www/html/rummy.bielu.pl'
                    cleanDestinationFolder: true
                    overwriteExistingFiles: true